### ISSUE TITLE
Error Building Utility_Functions from Source

### ISSUE THREAD

**Issue by njsch** [splashkit/splashkit-core#134]
Running from [This merge-commit](https://github.com/njsch/splashkit-core/commit/8eb2594d0c5037c6e21d7a84721ebae2cc46a39f), I run into the following compilation error when attempting to build Splashkit from source:

```
[ 20%] Building CXX object CMakeFiles/SplashKitBackend.dir/C/GitInit/njsch/splashkit-core/coresdk/src/backend/utility_functions.cpp.obj                
                                                                                                                       
C:/GitInit/njsch/splashkit-core/coresdk/src/backend/utility_functions.cpp: In function 'bool splashkit_lib::scan_dir_recursive(const string&, std::vector<std::__cxx11::basic_string<char>
>&)':                                                                                 C:/GitInit/njsch/splashkit-core/coresdk/src/backend/utility_functions.cpp:155:9:
error: 'DIR' was not declared in this scope                                                                                                           
                                       
         DIR *dirhnd;                                                                                                                                  
                                                                                                                       
         ^~~                                                                                                                                           
                                                                                                                    C:/GitInit/njsch/splashkit-core/coresdk/src/backend/utility_functions.cpp:155:9:
note: suggested alternative: 'CD_R'                                                                                                                   
                                       
         DIR *dirhnd;                                                                                                                                  
                                                                                                                       
         ^~~                                                                                                                                           
                                                                                                                  
         CD_R                                                                                                                                          
                                                                                                                   
C:/GitInit/njsch/splashkit-core/coresdk/src/backend/utility_functions.cpp:155:14: error: 'dirhnd' was not declared in this scope                       
                                                                                                                                  DIR *dirhnd;
                                                                                                                                                      
                                                                                                  
              ^~~~~~                                                                                                                                   
                                                                                                                       
C:/GitInit/njsch/splashkit-core/coresdk/src/backend/utility_functions.cpp:155:14: note: suggested alternative: 'VarAnd'                                
                                                                                                                       
         DIR *dirhnd;                                                                                                                                  
                                                                                                                                       ^~~~~~
                                                                                                                                                      
                                                                                                   
              VarAnd                                                                                                                                   
                                                                                                                       
C:/GitInit/njsch/splashkit-core/coresdk/src/backend/utility_functions.cpp:164:22: error: 'opendir' was not declared in this scope                      
                                                                                                                       
             dirhnd = opendir(directories[i].c_str());                                                                                                 
                                                                                                                       
                      ^~~~~~~                                                                                                                          
                                                                                                                         C:/GitInit/njsch/splashkit-core/coresdk/src/backend/utility_functions.cpp:164:22:
note: suggested alternative: 'open'
```

Did something go wrong with my merge, or is there actually a syntax error that needs to be fixed?

FYI @macite @alexcu @jakerenzella @jarmstrong
![MSYS2_screenshot](https://user-images.githubusercontent.com/56899272/96571883-e7427580-1317-11eb-9c55-99300c302b79.png)

**Comment by hugglesfox** [comment]
Probably caused by #103 / #125

**Comment by njsch** [comment]
Okay so not exactly sure how to do this.  Can check for Win platform with #if defined(_WIN32) and fonts dir will be in %windir%\Fonts.  Does the function simply require that the directory be opened?

**Comment by njsch** [comment]
@macite, still getting an issue but a different one this time (running Win10 v2004 and MSYS2 MinGW64):

``` [ 96%] Linking CXX executable /C/GitInit/njsch/splashkit-core/bin/sktest                                                                                                                                                                                                       
 C:/GitInit/njsch/splashkit-core/out/lib/libSplashKitBackend.a(utility_functions.cpp.obj):utility_functions.cpp:(.text+0xb96): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'                                 
 C:/GitInit/njsch/splashkit-core/out/lib/libSplashKitBackend.a(utility_functions.cpp.obj):utility_functions.cpp:(.text+0xbc5): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'                                 
 C:/GitInit/njsch/splashkit-core/out/lib/libSplashKitBackend.a(utility_functions.cpp.obj):utility_functions.cpp:(.text+0xbe5): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::operator*() const'                                               
 C:/GitInit/njsch/splashkit-core/out/lib/libSplashKitBackend.a(utility_functions.cpp.obj):utility_functions.cpp:(.text+0xc51): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::operator++()'                                                    
 C:/GitInit/njsch/splashkit-core/out/lib/libSplashKitBackend.a(utility_functions.cpp.obj):utility_functions.cpp:(.text+0xc62): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'                                 
 C:/GitInit/njsch/splashkit-core/out/lib/libSplashKitBackend.a(utility_functions.cpp.obj):utility_functions.cpp:(.text+0xc6e): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'                                 
 C:/GitInit/njsch/splashkit-core/out/lib/libSplashKitBackend.a(utility_functions.cpp.obj):utility_functions.cpp:(.text+0xc7a): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'                                 
 C:/GitInit/njsch/splashkit-core/out/lib/libSplashKitBackend.a(utility_functions.cpp.obj):utility_functions.cpp:(.text+0xcaf): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'                                 
 C:/GitInit/njsch/splashkit-core/out/lib/libSplashKitBackend.a(utility_functions.cpp.obj):utility_functions.cpp:(.text+0xcbb): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'                                 
 C:/GitInit/njsch/splashkit-core/out/lib/libSplashKitBackend.a(utility_functions.cpp.obj):utility_functions.cpp:(.text+0xcc7): more undefined references to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()' follow                    
 C:/GitInit/njsch/splashkit-core/out/lib/libSplashKitBackend.a(utility_functions.cpp.obj):utility_functions.cpp:(.text$_ZNSt10filesystem7__cxx1116filesystem_errorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt10error_code[_ZNSt10filesystem7__cxx1116filesystem_
 errorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt10error_code]+0x93): undefined reference to `std::filesystem::__cxx11::filesystem_error::_M_gen_what()'                                                                                                        
 C:/GitInit/njsch/splashkit-core/out/lib/libSplashKitBackend.a(utility_functions.cpp.obj):utility_functions.cpp:(.text$_ZNKSt10filesystem7__cxx1115directory_entry6statusEv[_ZNKSt10filesystem7__cxx1115directory_entry6statusEv]+0x14): undefined reference to `std::filesystem
 ::status(std::filesystem::__cxx11::path const&)'                                                                                                                                                                                                                               
 C:/GitInit/njsch/splashkit-core/out/lib/libSplashKitBackend.a(utility_functions.cpp.obj):utility_functions.cpp:(.text$_ZNSt10filesystem7__cxx1128recursive_directory_iteratorC1ERKNS0_4pathE[_ZNSt10filesystem7__cxx1128recursive_directory_iteratorC1ERKNS0_4pathE]+0x28): und
 efined reference to `std::filesystem::__cxx11::recursive_directory_iterator::recursive_directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)'                                                                        
 C:/GitInit/njsch/splashkit-core/out/lib/libSplashKitBackend.a(utility_functions.cpp.obj):utility_functions.cpp:(.text$_ZNSt10filesystem7__cxx114pathC1INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1_EERKT_NS1_6formatE[_ZNSt10filesystem7__cxx114pathC1INSt7__cxx1112
 basic_stringIcSt11char_traitsIcESaIcEEES1_EERKT_NS1_6formatE]+0x64): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'                                                                                                                                 
 C:/GitInit/njsch/splashkit-core/out/lib/libSplashKitBackend.a(utility_functions.cpp.obj):utility_functions.cpp:(.rdata$.refptr._ZNSt10filesystem7__cxx1116filesystem_errorD1Ev[.refptr._ZNSt10filesystem7__cxx1116filesystem_errorD1Ev]+0x0): undefined reference to `std::file
 system::__cxx11::filesystem_error::~filesystem_error()'                                                                                                                                                                                                                        
 C:/GitInit/njsch/splashkit-core/out/lib/libSplashKitBackend.a(utility_functions.cpp.obj):utility_functions.cpp:(.rdata$.refptr._ZTVNSt10filesystem7__cxx1116filesystem_errorE[.refptr._ZTVNSt10filesystem7__cxx1116filesystem_errorE]+0x0): undefined reference to `vtable for 
 std::filesystem::__cxx11::filesystem_error'                                                                                                                                                                                                                                    
 collect2.exe: error: ld returned 1 exit status                                                                                                                                                                                                                                 
 make[2]: *** [CMakeFiles/sktest.dir/build.make:431: /C/GitInit/njsch/splashkit-core/bin/sktest] Error 1                                                                                                                                                                        
 make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/sktest.dir/all] Error 2                                                                                                                                                                                                      
 make: *** [Makefile:130: all] Error 2                                                                                                                                                                                                                                          ```
![MSYS2_Screenshot](https://user-images.githubusercontent.com/56899272/97770242-8de30d80-1b85-11eb-8243-bc9726d83c16.png)
